# Generated by Django 4.2.4 on 2023-09-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('name3', models.CharField(max_length=100)),
                ('name4', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('image4', models.ImageField(upload_to='')),
                ('description1', models.CharField(max_length=300)),
                ('description2', models.CharField(max_length=300)),
                ('description3', models.CharField(max_length=300)),
                ('description4', models.CharField(max_length=300)),
                ('rating1', models.IntegerField(default='5')),
                ('rating2', models.IntegerField(default='5')),
                ('rating3', models.IntegerField(default='5')),
                ('rating4', models.IntegerField(default='5')),
            ],
        ),
    ]
