# Generated by Django 4.2.4 on 2023-09-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='description1',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='name1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='rating1',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='services',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='services',
            name='description4',
        ),
        migrations.RemoveField(
            model_name='services',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='services',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='services',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='services',
            name='name4',
        ),
        migrations.RemoveField(
            model_name='services',
            name='rating2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='rating3',
        ),
        migrations.RemoveField(
            model_name='services',
            name='rating4',
        ),
    ]
