# Generated by Django 4.2.4 on 2023-09-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_description1_services_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='selectservice',
            field=models.CharField(choices=[('periodic service', 'periodic service'), ('wheel allignment', 'wheel allignment'), ('car polish and Ceramic coating', 'car polish and Ceramic coating'), ('car wash', 'car wash')], default='car wash', max_length=300),
        ),
    ]
