# Generated by Django 4.2.4 on 2023-09-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='fueltype',
            new_name='fuel_type',
        ),
    ]
