# Generated by Django 4.2.4 on 2023-09-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_fueltype_book_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='timeslot',
            field=models.CharField(choices=[('8:00 am - 10:00 am', '8:00 am - 10:00 am'), ('10:00 am - 12:00 pm', '10:00 am - 12:00 pm'), ('12:00 am - 2:00 pm', '12:00 am - 2:00 pm'), ('3:00 am - 5:00 pm', '3:00 am - 5:00 pm'), ('5:00 am - 7:00 pm', '5:00 am - 7:00 pm')], default='8:00 am - 10:00 am', max_length=300),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
