# Generated by Django 4.2.4 on 2023-09-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_book_date_book_timeslot_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
